### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by calgara12** [TachiWeb/TachiWeb-Server#7]
Hello, first of all thanks for this application :)

Unfortunately when i run ```scripts/build.sh``` i get a permission error.
![capture](https://user-images.githubusercontent.com/28657023/30457976-e525dd86-99a9-11e7-95e3-9bddd0c4ef1a.PNG)

when i run the command as sudo i also get an error:
![1](https://user-images.githubusercontent.com/28657023/30458204-cb48f87a-99aa-11e7-869a-14c28d3998d8.PNG)

And then later i get this error:
![3](https://user-images.githubusercontent.com/28657023/30458215-d6e19980-99aa-11e7-8cd3-b181d14eeb46.PNG)

Thanks in advance :)

**Comment by null-dev** [comment]
Hi, thanks for the feedback!

The first error is because some of the permissions on your system are messed up. you should run these commands to fix it:
```
sudo chown -R $USER:$GROUP ~/.npm 
sudo chown -R $USER:$GROUP ~/.config 
```
Then you can run `scripts/build.sh` again.
More information on this can be found here: https://github.com/bower/bower/issues/2262

**Note: You can ignore all the `zip error: Nothing to do!` warnings. Those are normal!** 

There is also a pre-built version of this program available here if you don't want to go through the trouble of building it: http://ci.nulldev.xyz/job/TachiWeb-Server/lastSuccessfulBuild/artifact/TachiServer/build/libs/TachiServer-all-1.0.jar

**Comment by calgara12** [comment]
Thanks for your answer, I still got some errors, but i decided to go with the pre-built version :)

**Comment by null-dev** [comment]
Builds are now tested on Ubuntu + Arch + Mac.
